export const ADD_TO_CART = 'ADD_TO_CART'
export const DELETE_TO_CART = 'DELETE_TO_CART';
export const INCREMENT_PRODUCT = 'INCREMENT_PRODUCT';
export const DECREMENT_PRODUCT = 'DECREMENT_PRODUCT';
export const CONFORM_ORDER = 'CONFORM_ORDER';
export const GET_ADMIN_PRODUCT="GET_ADMIN_PRODUCT";
